### ISSUE TITLE
German press

### ISSUE THREAD

**Issue by 4goettma** [sa7mon/venmo-data#1]
https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fwww.heise.de%2Fnewsticker%2Fmeldung%2FDatenbank-von-oeffentlichen-Venmo-Transaktionen-auf-Github-4448178.html

https://www.heise.de/newsticker/meldung/Datenbank-von-oeffentlichen-Venmo-Transaktionen-auf-Github-4448178.html

https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fwww.golem.de%2Fnews%2Fdatenschutz-paypal-tochter-venmo-belaesst-transaktionen-im-internet-1906-141947.html

https://www.golem.de/news/datenschutz-paypal-tochter-venmo-belaesst-transaktionen-im-internet-1906-141947.html

**Comment by sa7mon** [comment]
Thanks for posting the links! Sorry, for the late response - I apparently wasn't watching the repo.

I've added the links to the README
