### ISSUE TITLE
Issue downloading torrent

### ISSUE THREAD

**Issue by maxleb-riftpay** [sa7mon/venmo-data#4]
The torrent does not appear to have any seeders and the HTTPS link isn't working. Is there any other way to download the data?

**Comment by sa7mon** [comment]
Thanks for bringing this to my attention. I've uploaded the original version as well as a CSV and Sqlite3 version to this Google Drive folder: https://drive.google.com/drive/folders/1m59TMADiwk3gArT-teUUOBlSKokq51ZL?usp=sharing
